### ISSUE TITLE
Overriding metrics queries is misleading

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#27]
When specifying specific queries in the "metric-reporting" configuration box, the help text below the box points to [this url](https://github.com/fossology/fossology/blob/a53e8a2536d40f96b3f3ad8b8c820f3078c5d260/install/fossdash/fossdash_metrics.yml) for an conf example.

The problem here is that the example is not up to date (the entries for `VERSION_INFO` and `LOG_COUNT_INFO` are missing).

In the logs, I get this output:
```
2020-08-24 14:41:01.707012
Fossology Instance UUID =  fossology-dev-2
'VERSION_INFO'
```

Instead of
```
2020-08-24 14:43:02.111762
Fossology Instance UUID =  fossology-dev-2
All data metrics Generated
publishing FossDash URL = http://influxdb:8086/write?db=fossology_db
sending file to influxDB = /srv/fossology/repository/fossdash/fossdash-publish.20200824_144302
token based authentication 
status code = 204
```

Two ideas to get this fixed in the long term:
1. instead of pointing to the GitHub file (complicated until the feature is not merged in master), we could create a Wiki page on GitHub, with explanation and a link to the file example (because it will be easier to update
2. Have a default value for `VERSION_INFO` and `LOG_COUNT_INFO` if they are not part of the overriding config - or at the very least, print an explicit error message in the logs.

**Comment by NicolasToussaint** [comment]
Otherwise, overriding the conf with this, as an example, works well:
```
# Example of fossdash metrics config file
QUERIES_NAME: [
    "number_of_users", "swh_200_count", "swh_404_count"]

QUERY:
  number_of_users: "SELECT count(u.*) AS users FROM users u;"
  swh_200_count: "SELECT count(*) from software_heritage where swh_status=200;"
  swh_404_count: "SELECT count(*) from software_heritage where swh_status=404;"

VERSION_INFO:
  display: "YES"    # NO, If don't want to display VERSION and BUILD info

LOG_COUNT_INFO:
  display: "YES"   # NO, If don't want to display ERROR, FATAL and WARNING count
```
